services:
  # Next.js app Dockerfile (dev version)
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - ./.env
    environment:
      # Explicitly set DATABASE_URL here because it points to the 'db' service
      DATABASE_URL: postgresql://user:password@db:5432/mydatabase?schema=public
      # You can also use this section to override variables from .env (if needed)
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432" # Optional: if you want to connect a GUI tool
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data

# "named volumes" that persist data, so your data doesn't disappear when containers are stopped or removed.
volumes:
  db_data: